version: '3.9'
services:
  bili_task:
    image: catlair/bilitools # 按需选择版本
    container_name: catlair_bilitools
    volumes: # 请注意路径是否正确
      - ./config/:/usr/src/app/config/
    tty: true
    env_file: .env # 请注意路径是否正确
