component: scf # 必填内容
name: ${env:COMPONENT_NAME}
org: ''
app: ''
stage: production
inputs:
  name: ${env:SCF_NAME}
  src: ./dist
  runtime: Nodejs12.16
  region: ${env:SCF_REGION}
  description: ${env:SCF_DESCRIPTION}
  handler: ${env:SCF_HANDLER}
  memorySize: ${env:SCF_MEMORY_SIZE}
  timeout: ${env:SCF_TIMEOUT}
  events:
    - timer: # 定时触发器
        parameters:
          # name: timer # 触发器名称，默认timer-${name}-${stage}
          name: ${env:SCF_TIMER_NAME} # 若要使用scf随机执行请勿修改触发器名
          cronExpression: ${env:BILI_CRON_EXPRESSION} # 每天22点43分55秒触发
          enable: ${env:BILI_IS_RUN}
  environment:
    variables:
      TENCENT_SECRET_ID: ${env:TENCENT_SECRET_ID}
      TENCENT_SECRET_KEY: ${env:TENCENT_SECRET_KEY}
  # For more information: https://github.com/serverless-components/tencent-scf/blob/master/docs/configure.md
